### ISSUE TITLE
Donation link

### ISSUE THREAD

**Issue by cr3ative** [xenova/chat-replay-downloader#10]
Hey Xenova, got any links to donate a lil something to you? You saved something very special to me. :)

**Comment by xenova** [comment]
Oh wow this is unexpected! 😄 I don't have a specific donation button, but I do have a PayPal if that is what you mean? admin@xenova.com

But you really don't have to... 😅 I make these projects open source just because so many other people have helped me with their open-source projects, so I'm just giving back and spreading the love!

**Comment by cr3ative** [comment]
Thanks ;)

**Comment by xenova** [comment]
@cr3ative Wow thank you!
