### ISSUE TITLE
Receiving Error after execution 

### ISSUE THREAD

**Issue by kenshin657** [xenova/chat-replay-downloader#19]
After running the program I receive this error at the end
`'list' is not recognized as an internal or external command, operable program or batch file. `

Any idea how to fix this?

**Comment by kenshin657** [comment]
This is how I ran the code
`python chat_replay_downloader.py https://www.youtube.com/watch?v=O-gMsO9pwdI&list=PLHtQDtiBQx3eaCkDqITLPSqX-7yljkjgp -output ex.csv    `

**Comment by xenova** [comment]
Okay that is very simple to fix:

Remember that "&" is a special symbol when working in a command line. It is used to run commands in the background among other things. In order to fix it, you need to wrap any text that contains it in annotation marks as follows:

`python chat_replay_downloader.py "https://www.youtube.com/watch?v=O-gMsO9pwdI&list=PLHtQDtiBQx3eaCkDqITLPSqX-7yljkjgp" -output ex.csv`
