### ISSUE TITLE
Some new features

### ISSUE THREAD

**Issue by 9001** [xenova/chat-replay-downloader#20]
Hey there, and thanks for making this! I've been adding some minor features to cover my own usecases, and was wondering if you'd like to have some of this merged in? I'd be happy to create some PR's all depending on how you'd like it wrapped :>

with all included, it currently looks like this: https://ocv.me/dev/?chat_replay_downloader.py

the following changes are fairly clean and could mostly be copied over as-is:
* use `videoOffsetTimeMsec` rather than `timestampText` when available, for subsecond precision
* in json output, include `authorExternalChannelId` as `author_id` to separate users with the same display name
* in json output, include user attributes (moderator flag etc, taken from `authorBadges`)
* in `__print_item`, have an additional try/catch around `print(safe_string)` in case the stdout codec is not unicode

now these i'm a bit uncertain about... maybe i'm just fixing symptoms rather than the root cause:
* use `item.get('time_text', None)` rather than `item['time_text']` in `message_to_string` as some messages don't appear to have this key at all
* another conditional for the presence of `time_text` in `__parse_item`

additionally, i added a crude hack to persist the original json replies from youtube in a logfile (in addition to the generated json output) so I didn't have to call youtube's servers all the time when testing changes... was super useful, but would need a total rewrite if it's a feature to keep :p 

most of that is the `logfile` stuff in `get_youtube_messages` and `__main__`, plus the new `get_chat_replay_from_json()` which replaces the `__get_live_info` and `__get_replay_info` functions to grab responses from the logfile rather than youtube, so it's by all means not pretty

and finally, the reason i wanted subsecond precision in the first place :p https://twitter.com/tripflag/status/1317862794725855235

**Comment by xenova** [comment]
This is awesome! So cool to see others use and modify the code! :) I could totally add your code to the program. I don't mind whether you create a pull request or if you just allow me to look at your code and add where necessary (depends if you want to become a contributor on GitHub or not).

Actually, the reason I created the tool in the first place was to analyse the speed at which chat messages were sent in a live stream. Initially, I used videoOffsetTimeMsec to calculate this, but what I found is that it was completely different to the text that was shown on the screen - up to 10 seconds difference in some cases (somehow). So, what I ended up doing is including the timestamp of the message (the unix/epoch time it was sent) and using the timestamp text to mark the offset of the video. Basically, the videoOffsetTimeMsec completely disagreed with the text on YouTube - and I made the assumption that people would rather have the exact time shown on the website rather than the (perhaps more accurate) videoOffsetTimeMsec. I also thought that in any case where a higher precision was needed, people could use the unix/epoch time.

I will have time this weekend to do all the code review and merging.

**Comment by 9001** [comment]
Oh if you're alright with picking the good parts yourself then please go ahead, that's perfect :> thx!

Shame to hear about the occasional videoOffsetTimeMsec desync though - maybe that happens in some cases when the streamer gets disconnected or something? It's curious because all of my rips seem to be accurate so far, even one where I recall the streamer mentioned getting disconnected... I think it would be a good idea to include it in the json output anyways (maybe as a separate field) so you're free to make the best of it later 👍

**Comment by xenova** [comment]
> actually come to think of it, at first I did try to combine the H:M:S and the unix/epoch, but then you get the complexity of comparing all the messages to figure out the initial epoch of 00:00... so I quickly gave up on that heh

Yep that's exactly what I did first! I even had an implementation where it would constantly update the start time by averaging all the timestamps, but decided against that once I realised I didn't really need it. Sure, I can add it as an extra field. I'll update the code this weekend when I have time.

**Comment by xenova** [comment]
I'll add this as a comment while I add your changes to the code:
Another reason I chose to use the timestamp was because `videoOffsetTimeMsec` did not work for negative times. For example,

`{'message': 'Been waiting for this!!', 'author': 'Jess Payne', 'timestamp': 1603996769452719, 'author_id': 'UCEtIrPQBfLO5o__BOcB4qlw', 'time_text': '-1:34', 'time_in_seconds': -94, 'videoOffsetTimeMsec': '0'}` 
I'm making it so that this is what is returned, and the use can choose what data they want to use.

Of course, later on this is fine:
`{"message": "Hey Hey", "author": "Anavay Mudholkar", "timestamp": 1603996921040686, "author_id": "UCuZE6J6V3dyITYlk3T_uhsw", "time_text": "0:55", "time_in_seconds": 55, "videoOffsetTimeMsec": "55406"`
