### ISSUE TITLE
Add support for YouTube member only live stream.

### ISSUE THREAD

**Issue by MinkiNTN** [xenova/chat-replay-downloader#21]
I noticed when trying to download chat replay from a YouTube "member only" live stream, the program returns `Video does not have a chat replay.`, which is not true. Is it possible to add support so that chat replay can be downloaded from these streams by passing in a suitable cookie?

**Comment by xenova** [comment]
This is a great idea! 👍 I unfortunately don't have any videos to test on (since I am not a member of any channel). Could I perhaps let you test the code before I add these changes to the master branch? The relevant lines of code are 116-129.
[chat_replay_downloader.zip](https://github.com/xenova/chat-replay-downloader/files/5470917/chat_replay_downloader.zip)

You should be able to pass a cookies.txt file with `-cookies <file>`. For example:
`python chat_replay_downloader.py <url> -cookies cookies.txt`

Let me know if that works! 😃

**Comment by MinkiNTN** [comment]
I just tested and it works prefectly 👍 

Another question that I think is kinda related (since I'm not that good with Python :D): I'm importing your script like this `from chat_replay_downloader import get_youtube_messages`, how would I insert the cookies to that because I think it happens before.

**Comment by xenova** [comment]
Okay great! 👍 

Oh right, I should explicitly mention how to import from the main module. You can do so as follows:

```python
from chat_replay_downloader import ChatReplayDownloader

session = ChatReplayDownloader(cookies='cookies.txt')
messages = session.get_chat_replay('url')

```

**Comment by MinkiNTN** [comment]
Awesome! Thanks again for the great work 👍 

I don't know if I should close the issue so I'm gonna leave you to it.

**Comment by xenova** [comment]
I'll close it with the next update! 😃
