### ISSUE TITLE
Help much appreciated

### ISSUE THREAD

**Issue by matthewtechno** [xenova/chat-replay-downloader#42]
Really sorry to have to do this but I have no knowledge of Python and this is my last hope. I live streamed a wedding and trimmed it not realising YouTube removed live chat replay if you trim. The couple had lots of lovely messages from family there and I really need to get them back. If I share the video URL, can anybody help me with this? Thank you so much.

**Comment by xenova** [comment]
Hi Matthew. Since YouTube does not have an API for retrieving past livestream comments, the only way (to my knowledge) to retrieve chat messages is to essentially open the url and simulate "getting" the next bunch of messages: which is what the tool does. So, if it is not visible on the YouTube page, it most likely will not be able to be retrieved using the tool.

If you wish to send the ID (here or via email), I can try some things, but I cannot promise anything. 

Unfortunately YouTube has had this "feature" (that trimming the video causes the live chat replay to be deleted) for more than two years... [for example](https://www.reddit.com/r/youtubegaming/comments/949uku/is_it_planned_to_let_us_trim_livestreams_but_keep/). Are you perhaps able to undo the trim? I am unsure whether that would fix it, but I suppose it is worth a try.

Hope this helps!
