### ISSUE TITLE
JSONDecodeError session request

### ISSUE THREAD

**Issue by dpppde** [xenova/chat-replay-downloader#48]
I get this error sometimes
![IMG_20210128_155830](https://user-images.githubusercontent.com/41359860/106115742-aa421680-6183-11eb-8381-6df751feb2ac.jpg)

**Comment by xenova** [comment]
Hi there, thanks for posting this issue. I have myself noticed that this sometimes occurs. However, the problem seems to be on YouTube's side. In fact, it seems to be happening on almost every YouTube video I have tested recently.

As an example, http://youtube.com/live_chat/get_live_chat?continuation=0ofMyANhGlhDaWtxSndvWVZVTnJWRU5PZFZFeWJVZG1Well0VTNCSWNHRjZaVjluRWd0Q1dFZzBZWHAzVjNKa1VSb1Q2cWpkdVFFTkNndENXRWcwWVhwM1YzSmtVU0FCMAGCAQIIAQ%3D%3D&pbj=1&hidden=false returns the exact same text:
```
)]}'
{"reload":"now"}
```

Nevertheless, I am looking into a way to fix it. I might have to use another endpoint.

**Comment by xenova** [comment]
## An update to those waiting:
I have **found the problem** and I will fix it as soon as possible.

In short, YouTube removed support for an endpoint which this tool (and many others) used to get chat. They removed https://www.youtube.com/live_chat_replay/get_live_chat_replay and are now using https://www.youtube.com/youtubei/v1/live_chat/get_live_chat_replay and https://www.youtube.com/youtubei/v1/live_chat/get_live_chat.

**Comment by xenova** [comment]
Alright - I've been working a lot recently to get an updated/fixed version out for you all to use and test... and I think the `package` branch is ready for use. I still need to add a lot of documentation, but this will be much more useful than the current version in `master` (which doesn't work currently due to YouTube API endpoint changes).

This version is **much** more advanced than the original version. Some of the options are slightly different from version 1, but the help command (`chat_replay_downloader -h`) should assist you in the meantime while I write better documentation. 

### You can install it using `pip install chat-replay-downloader` (see https://pypi.org/project/chat-replay-downloader/ for more info).

Please let me know your thoughts and feel free to give suggestions! You can always post an issue or even create a pull request.
