### ISSUE TITLE
[YouTube] Support super chats

### ISSUE THREAD

**Issue by libjared** [xenova/chat-replay-downloader#7]
Super chats are donations to a partnered YouTube streamer.

- have messages if the donation amount is enough (for USD, this is $2 or greater)
- pin themselves to the top of the chat window (up to 5 hours for the max donation. For USD, this is $500)
- are colored based on the amount donated
- can be made in currencies other than USD

Currently no super chat data is saved. Ideally the output would have several additional fields: color, pin duration, amount, and the original currency code. And the presence of `amount` would differentiate super chats from regular chat.

Example video with a large number of super chats: https://www.youtube.com/watch?v=UlemRwXYWHg

**Comment by xenova** [comment]
Thanks for the suggestion! I've been adding it and it's almost done!

What other information would you like to show? Currently I have the following:
- Colours (For some reason it's in a format like "4280150454", and I'm not sure how that compares to RGB
  -  The colour of the heading and
  - the colour of the body of the message
- The amount in a given currency (e.g. $5.00)

and all the other information every other message has (text, timestamp, etc.)

**Comment by libjared** [comment]
Cool!
Yeah, those data points are all that I can think of. I googled `4280150454` and it led me to here:
https://docs-flutter-io.firebaseapp.com/flutter/material/Colors/tealAccent-constant.html
Suggesting that it was a teal super chat. If you convert it to hex, it's ARGB: FF1DE9B6. I don't mind which final format we pick. We could leave it as-is, or converted to a `#`-prefixed HTML color. Since HTML colors are RGB[A] we could probably just drop the alpha since I doubt there will ever be a transparent super chat. `4280150454 & 0xFFFFFF = #1DE9B6`

**Comment by xenova** [comment]
Great! Thanks for that info.

I've actually been working on adding it for the past couple of hours and for some reason, there are cases where there are transparent super chats. I'll add it in two formats I suppose, rgba array and # prefixed HTML colour. They are indeed ARGB colours, and I can convert accordingly.


I'm quite close to getting it to work, but there are a ton of strange edge cases. In the example video URL, after getting the JSON (see attached txt file, since github doesn't allow JSON)
[get_live_chat_replay.txt](https://github.com/xenova/chat-replay-downloader/files/5011360/get_live_chat_replay.txt)

of the chat info, there are a few important fields that are related to super chat messages, namely:
'liveChatPaidMessageRenderer','liveChatMembershipItemRenderer','liveChatPaidStickerRenderer' and 'liveChatTickerPaidMessageItemRenderer'. If you see any I missed, let me know 👍

**Comment by xenova** [comment]
That list has been updated to include all the following:

```
	__TYPES_OF_SUPER_CHAT_MESSAGES = [
		'liveChatTickerPaidStickerItemRenderer',
		'liveChatTickerPaidMessageItemRenderer',
		'liveChatMembershipItemRenderer',
		'liveChatTickerSponsorItemRenderer',
		'liveChatPaidMessageRenderer',
		'liveChatPaidStickerRenderer'
	]
	__TYPES_OF_MESSAGES_TO_IGNORE = [
		'liveChatViewerEngagementMessageRenderer', # message saying Live Chat replay is on
		'liveChatPlaceholderItemRenderer', # placeholder
		'liveChatModeChangeMessageRenderer' # e.g. slow mode enabled
	]

	__TYPES_OF_KNOWN_MESSAGES = [
		'liveChatTextMessageRenderer'
	] + __TYPES_OF_MESSAGES_TO_IGNORE + __TYPES_OF_SUPER_CHAT_MESSAGES
```

So, by selecting the option to display super chat messages, you will get TYPES_OF_SUPER_CHAT_MESSAGES, otherwise you will just get 'liveChatTextMessageRenderer' (the normal one, which is what we had previously)

And then, all items matching any of:
```
	'timestampUsec',
	'authorName',
	'purchaseAmountText',
	'message',
	'headerBackgroundColor',
	'bodyBackgroundColor',
	'timestampText',
	'amount',
	'durationSec',
	'detailText',
	'headerSubtext',
	'backgroundColor'
```


Let me know if this sounds like a good idea. 👍  (The above may be renames slightly)

**Comment by xenova** [comment]
Okay I will finish it off tomorrow - but let me know if you have any other questions in the meantime 👍 🔥

**Comment by xenova** [comment]
@libjared Okay - almost done! (So many small little things to worry about).

Just a question, 
![image](https://user-images.githubusercontent.com/26504141/89128111-8c0c9e00-d4f3-11ea-895b-7cf454881c7b.png)

some super chat messages don't have messages, but have animated stickers. Do you need access to the sticker url?

Otherwise, when I am done with this update, you can test it out and let me know what things are missed and I will try my best to add it.

**Comment by xenova** [comment]
Okay, new update is live (d65753c) - let me know if it works 👍

**Comment by xnaas** [comment]
The amount gets logged to console, but not to the outputted file (at least in the case of a text file).

**Comment by xenova** [comment]
Okay I can account for this, however, if you need more information stored, I would not recommend writing this data to text files. Instead, you should rather write it to a .json - as they have far better structure than text files.

**Comment by xenova** [comment]
@xnaas Let me know if this is better (efca2f8)
[For example](examples/superchat.txt)

**Comment by jarett-lee** [comment]
That's really cool, thanks. I agree, json is probably a better format for this.

**Comment by xnaas** [comment]
Yeah looks good, @xenova, I appreciate it. 😃
